# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fib-entry.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fib-entry.proto',
  package='ndn_message',
  serialized_pb='\n\x0f\x66ib-entry.proto\x12\x0bndn_message\"\x9c\x02\n\x0f\x46ibEntryMessage\x12\x39\n\tfib_entry\x18\x80\x01 \x02(\x0b\x32%.ndn_message.FibEntryMessage.FibEntry\x1a\x19\n\x04Name\x12\x11\n\tcomponent\x18\x08 \x03(\x0c\x1a.\n\rNextHopRecord\x12\x0f\n\x07\x66\x61\x63\x65_id\x18i \x02(\r\x12\x0c\n\x04\x63ost\x18j \x02(\r\x1a\x82\x01\n\x08\x46ibEntry\x12/\n\x04name\x18\x07 \x02(\x0b\x32!.ndn_message.FibEntryMessage.Name\x12\x45\n\x10next_hop_records\x18\x81\x01 \x03(\x0b\x32*.ndn_message.FibEntryMessage.NextHopRecord')




_FIBENTRYMESSAGE_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='ndn_message.FibEntryMessage.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='component', full_name='ndn_message.FibEntryMessage.Name.component', index=0,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=111,
  serialized_end=136,
)

_FIBENTRYMESSAGE_NEXTHOPRECORD = _descriptor.Descriptor(
  name='NextHopRecord',
  full_name='ndn_message.FibEntryMessage.NextHopRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='face_id', full_name='ndn_message.FibEntryMessage.NextHopRecord.face_id', index=0,
      number=105, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cost', full_name='ndn_message.FibEntryMessage.NextHopRecord.cost', index=1,
      number=106, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=138,
  serialized_end=184,
)

_FIBENTRYMESSAGE_FIBENTRY = _descriptor.Descriptor(
  name='FibEntry',
  full_name='ndn_message.FibEntryMessage.FibEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ndn_message.FibEntryMessage.FibEntry.name', index=0,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next_hop_records', full_name='ndn_message.FibEntryMessage.FibEntry.next_hop_records', index=1,
      number=129, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=187,
  serialized_end=317,
)

_FIBENTRYMESSAGE = _descriptor.Descriptor(
  name='FibEntryMessage',
  full_name='ndn_message.FibEntryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fib_entry', full_name='ndn_message.FibEntryMessage.fib_entry', index=0,
      number=128, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_FIBENTRYMESSAGE_NAME, _FIBENTRYMESSAGE_NEXTHOPRECORD, _FIBENTRYMESSAGE_FIBENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=33,
  serialized_end=317,
)

_FIBENTRYMESSAGE_NAME.containing_type = _FIBENTRYMESSAGE;
_FIBENTRYMESSAGE_NEXTHOPRECORD.containing_type = _FIBENTRYMESSAGE;
_FIBENTRYMESSAGE_FIBENTRY.fields_by_name['name'].message_type = _FIBENTRYMESSAGE_NAME
_FIBENTRYMESSAGE_FIBENTRY.fields_by_name['next_hop_records'].message_type = _FIBENTRYMESSAGE_NEXTHOPRECORD
_FIBENTRYMESSAGE_FIBENTRY.containing_type = _FIBENTRYMESSAGE;
_FIBENTRYMESSAGE.fields_by_name['fib_entry'].message_type = _FIBENTRYMESSAGE_FIBENTRY
DESCRIPTOR.message_types_by_name['FibEntryMessage'] = _FIBENTRYMESSAGE

class FibEntryMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Name(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _FIBENTRYMESSAGE_NAME

    # @@protoc_insertion_point(class_scope:ndn_message.FibEntryMessage.Name)

  class NextHopRecord(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _FIBENTRYMESSAGE_NEXTHOPRECORD

    # @@protoc_insertion_point(class_scope:ndn_message.FibEntryMessage.NextHopRecord)

  class FibEntry(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _FIBENTRYMESSAGE_FIBENTRY

    # @@protoc_insertion_point(class_scope:ndn_message.FibEntryMessage.FibEntry)
  DESCRIPTOR = _FIBENTRYMESSAGE

  # @@protoc_insertion_point(class_scope:ndn_message.FibEntryMessage)


# @@protoc_insertion_point(module_scope)
