# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sync-state.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sync-state.proto',
  package='Sync',
  serialized_pb='\n\x10sync-state.proto\x12\x04Sync\"\xc1\x01\n\tSyncState\x12\x0c\n\x04name\x18\x01 \x02(\t\x12(\n\x04type\x18\x02 \x02(\x0e\x32\x1a.Sync.SyncState.ActionType\x12$\n\x05seqno\x18\x03 \x01(\x0b\x32\x15.Sync.SyncState.SeqNo\x1a%\n\x05SeqNo\x12\x0b\n\x03seq\x18\x01 \x02(\x04\x12\x0f\n\x07session\x18\x02 \x02(\x04\"/\n\nActionType\x12\n\n\x06UPDATE\x10\x00\x12\n\n\x06\x44\x45LETE\x10\x01\x12\t\n\x05OTHER\x10\x02\"+\n\x0cSyncStateMsg\x12\x1b\n\x02ss\x18\x01 \x03(\x0b\x32\x0f.Sync.SyncState')



_SYNCSTATE_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='Sync.SyncState.ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UPDATE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DELETE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=173,
  serialized_end=220,
)


_SYNCSTATE_SEQNO = _descriptor.Descriptor(
  name='SeqNo',
  full_name='Sync.SyncState.SeqNo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='Sync.SyncState.SeqNo.seq', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session', full_name='Sync.SyncState.SeqNo.session', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=134,
  serialized_end=171,
)

_SYNCSTATE = _descriptor.Descriptor(
  name='SyncState',
  full_name='Sync.SyncState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Sync.SyncState.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='Sync.SyncState.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seqno', full_name='Sync.SyncState.seqno', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SYNCSTATE_SEQNO, ],
  enum_types=[
    _SYNCSTATE_ACTIONTYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=220,
)


_SYNCSTATEMSG = _descriptor.Descriptor(
  name='SyncStateMsg',
  full_name='Sync.SyncStateMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ss', full_name='Sync.SyncStateMsg.ss', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=222,
  serialized_end=265,
)

_SYNCSTATE_SEQNO.containing_type = _SYNCSTATE;
_SYNCSTATE.fields_by_name['type'].enum_type = _SYNCSTATE_ACTIONTYPE
_SYNCSTATE.fields_by_name['seqno'].message_type = _SYNCSTATE_SEQNO
_SYNCSTATE_ACTIONTYPE.containing_type = _SYNCSTATE;
_SYNCSTATEMSG.fields_by_name['ss'].message_type = _SYNCSTATE
DESCRIPTOR.message_types_by_name['SyncState'] = _SYNCSTATE
DESCRIPTOR.message_types_by_name['SyncStateMsg'] = _SYNCSTATEMSG

class SyncState(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class SeqNo(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _SYNCSTATE_SEQNO

    # @@protoc_insertion_point(class_scope:Sync.SyncState.SeqNo)
  DESCRIPTOR = _SYNCSTATE

  # @@protoc_insertion_point(class_scope:Sync.SyncState)

class SyncStateMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SYNCSTATEMSG

  # @@protoc_insertion_point(class_scope:Sync.SyncStateMsg)


# @@protoc_insertion_point(module_scope)
