# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: channel-status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='channel-status.proto',
  package='ndn_message',
  syntax='proto2',
  serialized_pb=_b('\n\x14\x63hannel-status.proto\x12\x0bndn_message\"\x85\x01\n\x14\x43hannelStatusMessage\x12H\n\x0e\x63hannel_status\x18\x82\x01 \x03(\x0b\x32/.ndn_message.ChannelStatusMessage.ChannelStatus\x1a#\n\rChannelStatus\x12\x12\n\tlocal_uri\x18\x81\x01 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CHANNELSTATUSMESSAGE_CHANNELSTATUS = _descriptor.Descriptor(
  name='ChannelStatus',
  full_name='ndn_message.ChannelStatusMessage.ChannelStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='local_uri', full_name='ndn_message.ChannelStatusMessage.ChannelStatus.local_uri', index=0,
      number=129, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=171,
)

_CHANNELSTATUSMESSAGE = _descriptor.Descriptor(
  name='ChannelStatusMessage',
  full_name='ndn_message.ChannelStatusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_status', full_name='ndn_message.ChannelStatusMessage.channel_status', index=0,
      number=130, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CHANNELSTATUSMESSAGE_CHANNELSTATUS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=171,
)

_CHANNELSTATUSMESSAGE_CHANNELSTATUS.containing_type = _CHANNELSTATUSMESSAGE
_CHANNELSTATUSMESSAGE.fields_by_name['channel_status'].message_type = _CHANNELSTATUSMESSAGE_CHANNELSTATUS
DESCRIPTOR.message_types_by_name['ChannelStatusMessage'] = _CHANNELSTATUSMESSAGE

ChannelStatusMessage = _reflection.GeneratedProtocolMessageType('ChannelStatusMessage', (_message.Message,), dict(

  ChannelStatus = _reflection.GeneratedProtocolMessageType('ChannelStatus', (_message.Message,), dict(
    DESCRIPTOR = _CHANNELSTATUSMESSAGE_CHANNELSTATUS,
    __module__ = 'channel_status_pb2'
    # @@protoc_insertion_point(class_scope:ndn_message.ChannelStatusMessage.ChannelStatus)
    ))
  ,
  DESCRIPTOR = _CHANNELSTATUSMESSAGE,
  __module__ = 'channel_status_pb2'
  # @@protoc_insertion_point(class_scope:ndn_message.ChannelStatusMessage)
  ))
_sym_db.RegisterMessage(ChannelStatusMessage)
_sym_db.RegisterMessage(ChannelStatusMessage.ChannelStatus)


# @@protoc_insertion_point(module_scope)
