# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control-parameters.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='control-parameters.proto',
  package='ndn_message',
  serialized_pb='\n\x18\x63ontrol-parameters.proto\x12\x0bndn_message\"\x91\x06\n\x16\x43ontrolParametersTypes\x1a\x19\n\x04Name\x12\x11\n\tcomponent\x18\x08 \x03(\x0c\x1a\x42\n\x08Strategy\x12\x36\n\x04name\x18\x07 \x02(\x0b\x32(.ndn_message.ControlParametersTypes.Name\x1a\x90\x02\n\x11\x43ontrolParameters\x12\x36\n\x04name\x18\x07 \x01(\x0b\x32(.ndn_message.ControlParametersTypes.Name\x12\x0f\n\x07\x66\x61\x63\x65_id\x18i \x01(\x04\x12\x0b\n\x03uri\x18r \x01(\t\x12\x1d\n\x15local_control_feature\x18n \x01(\x04\x12\x0e\n\x06origin\x18o \x01(\x04\x12\x0c\n\x04\x63ost\x18j \x01(\x04\x12\r\n\x05\x66lags\x18l \x01(\x04\x12>\n\x08strategy\x18k \x01(\x0b\x32,.ndn_message.ControlParametersTypes.Strategy\x12\x19\n\x11\x65xpiration_period\x18m \x01(\x04\x1a\x98\x01\n\x19\x43ontrolParametersResponse\x12\x13\n\x0bstatus_code\x18\x66 \x02(\x04\x12\x13\n\x0bstatus_text\x18g \x02(\t\x12Q\n\x12\x63ontrol_parameters\x18h \x03(\x0b\x32\x35.ndn_message.ControlParametersTypes.ControlParameters\x1am\n\x18\x43ontrolParametersMessage\x12Q\n\x12\x63ontrol_parameters\x18h \x02(\x0b\x32\x35.ndn_message.ControlParametersTypes.ControlParameters\x1a{\n ControlParametersResponseMessage\x12W\n\x10\x63ontrol_response\x18\x65 \x02(\x0b\x32=.ndn_message.ControlParametersTypes.ControlParametersResponse')




_CONTROLPARAMETERSTYPES_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='ndn_message.ControlParametersTypes.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='component', full_name='ndn_message.ControlParametersTypes.Name.component', index=0,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=68,
  serialized_end=93,
)

_CONTROLPARAMETERSTYPES_STRATEGY = _descriptor.Descriptor(
  name='Strategy',
  full_name='ndn_message.ControlParametersTypes.Strategy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ndn_message.ControlParametersTypes.Strategy.name', index=0,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=95,
  serialized_end=161,
)

_CONTROLPARAMETERSTYPES_CONTROLPARAMETERS = _descriptor.Descriptor(
  name='ControlParameters',
  full_name='ndn_message.ControlParametersTypes.ControlParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ndn_message.ControlParametersTypes.ControlParameters.name', index=0,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='face_id', full_name='ndn_message.ControlParametersTypes.ControlParameters.face_id', index=1,
      number=105, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uri', full_name='ndn_message.ControlParametersTypes.ControlParameters.uri', index=2,
      number=114, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_control_feature', full_name='ndn_message.ControlParametersTypes.ControlParameters.local_control_feature', index=3,
      number=110, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origin', full_name='ndn_message.ControlParametersTypes.ControlParameters.origin', index=4,
      number=111, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cost', full_name='ndn_message.ControlParametersTypes.ControlParameters.cost', index=5,
      number=106, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='ndn_message.ControlParametersTypes.ControlParameters.flags', index=6,
      number=108, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='ndn_message.ControlParametersTypes.ControlParameters.strategy', index=7,
      number=107, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiration_period', full_name='ndn_message.ControlParametersTypes.ControlParameters.expiration_period', index=8,
      number=109, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=164,
  serialized_end=436,
)

_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSE = _descriptor.Descriptor(
  name='ControlParametersResponse',
  full_name='ndn_message.ControlParametersTypes.ControlParametersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='ndn_message.ControlParametersTypes.ControlParametersResponse.status_code', index=0,
      number=102, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status_text', full_name='ndn_message.ControlParametersTypes.ControlParametersResponse.status_text', index=1,
      number=103, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='control_parameters', full_name='ndn_message.ControlParametersTypes.ControlParametersResponse.control_parameters', index=2,
      number=104, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=439,
  serialized_end=591,
)

_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSMESSAGE = _descriptor.Descriptor(
  name='ControlParametersMessage',
  full_name='ndn_message.ControlParametersTypes.ControlParametersMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='control_parameters', full_name='ndn_message.ControlParametersTypes.ControlParametersMessage.control_parameters', index=0,
      number=104, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=593,
  serialized_end=702,
)

_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSEMESSAGE = _descriptor.Descriptor(
  name='ControlParametersResponseMessage',
  full_name='ndn_message.ControlParametersTypes.ControlParametersResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='control_response', full_name='ndn_message.ControlParametersTypes.ControlParametersResponseMessage.control_response', index=0,
      number=101, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=704,
  serialized_end=827,
)

_CONTROLPARAMETERSTYPES = _descriptor.Descriptor(
  name='ControlParametersTypes',
  full_name='ndn_message.ControlParametersTypes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_CONTROLPARAMETERSTYPES_NAME, _CONTROLPARAMETERSTYPES_STRATEGY, _CONTROLPARAMETERSTYPES_CONTROLPARAMETERS, _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSE, _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSMESSAGE, _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSEMESSAGE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=827,
)

_CONTROLPARAMETERSTYPES_NAME.containing_type = _CONTROLPARAMETERSTYPES;
_CONTROLPARAMETERSTYPES_STRATEGY.fields_by_name['name'].message_type = _CONTROLPARAMETERSTYPES_NAME
_CONTROLPARAMETERSTYPES_STRATEGY.containing_type = _CONTROLPARAMETERSTYPES;
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERS.fields_by_name['name'].message_type = _CONTROLPARAMETERSTYPES_NAME
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERS.fields_by_name['strategy'].message_type = _CONTROLPARAMETERSTYPES_STRATEGY
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERS.containing_type = _CONTROLPARAMETERSTYPES;
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSE.fields_by_name['control_parameters'].message_type = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERS
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSE.containing_type = _CONTROLPARAMETERSTYPES;
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSMESSAGE.fields_by_name['control_parameters'].message_type = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERS
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSMESSAGE.containing_type = _CONTROLPARAMETERSTYPES;
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSEMESSAGE.fields_by_name['control_response'].message_type = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSE
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSEMESSAGE.containing_type = _CONTROLPARAMETERSTYPES;
DESCRIPTOR.message_types_by_name['ControlParametersTypes'] = _CONTROLPARAMETERSTYPES

class ControlParametersTypes(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Name(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CONTROLPARAMETERSTYPES_NAME

    # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes.Name)

  class Strategy(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CONTROLPARAMETERSTYPES_STRATEGY

    # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes.Strategy)

  class ControlParameters(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERS

    # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes.ControlParameters)

  class ControlParametersResponse(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSE

    # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes.ControlParametersResponse)

  class ControlParametersMessage(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSMESSAGE

    # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes.ControlParametersMessage)

  class ControlParametersResponseMessage(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSEMESSAGE

    # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes.ControlParametersResponseMessage)
  DESCRIPTOR = _CONTROLPARAMETERSTYPES

  # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes)


# @@protoc_insertion_point(module_scope)
