# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control-parameters.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='control-parameters.proto',
  package='ndn_message',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x18\x63ontrol-parameters.proto\x12\x0bndn_message\"\xb2\x07\n\x16\x43ontrolParametersTypes\x1a\x19\n\x04Name\x12\x11\n\tcomponent\x18\x08 \x03(\x0c\x1a\x42\n\x08Strategy\x12\x36\n\x04name\x18\x07 \x02(\x0b\x32(.ndn_message.ControlParametersTypes.Name\x1a\xb1\x03\n\x11\x43ontrolParameters\x12\x36\n\x04name\x18\x07 \x01(\x0b\x32(.ndn_message.ControlParametersTypes.Name\x12\x0f\n\x07\x66\x61\x63\x65_id\x18i \x01(\x04\x12\x0b\n\x03uri\x18r \x01(\t\x12\x12\n\tlocal_uri\x18\x81\x01 \x01(\t\x12\x0e\n\x06origin\x18o \x01(\x04\x12\x0c\n\x04\x63ost\x18j \x01(\x04\x12\x11\n\x08\x63\x61pacity\x18\x83\x01 \x01(\x04\x12\x0e\n\x05\x63ount\x18\x84\x01 \x01(\x04\x12\r\n\x05\x66lags\x18l \x01(\x04\x12\x0c\n\x04mask\x18p \x01(\x04\x12>\n\x08strategy\x18k \x01(\x0b\x32,.ndn_message.ControlParametersTypes.Strategy\x12\x19\n\x11\x65xpiration_period\x18m \x01(\x04\x12\x19\n\x10\x66\x61\x63\x65_persistency\x18\x85\x01 \x01(\x04\x12)\n base_congestion_marking_interval\x18\x87\x01 \x01(\x04\x12%\n\x1c\x64\x65\x66\x61ult_congestion_threshold\x18\x88\x01 \x01(\x04\x12\x0c\n\x03mtu\x18\x89\x01 \x01(\x04\x1a\x98\x01\n\x19\x43ontrolParametersResponse\x12\x13\n\x0bstatus_code\x18\x66 \x02(\x04\x12\x13\n\x0bstatus_text\x18g \x02(\t\x12Q\n\x12\x63ontrol_parameters\x18h \x03(\x0b\x32\x35.ndn_message.ControlParametersTypes.ControlParameters\x1am\n\x18\x43ontrolParametersMessage\x12Q\n\x12\x63ontrol_parameters\x18h \x02(\x0b\x32\x35.ndn_message.ControlParametersTypes.ControlParameters\x1a{\n ControlParametersResponseMessage\x12W\n\x10\x63ontrol_response\x18\x65 \x02(\x0b\x32=.ndn_message.ControlParametersTypes.ControlParametersResponse')
)




_CONTROLPARAMETERSTYPES_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='ndn_message.ControlParametersTypes.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='component', full_name='ndn_message.ControlParametersTypes.Name.component', index=0,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=93,
)

_CONTROLPARAMETERSTYPES_STRATEGY = _descriptor.Descriptor(
  name='Strategy',
  full_name='ndn_message.ControlParametersTypes.Strategy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ndn_message.ControlParametersTypes.Strategy.name', index=0,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=161,
)

_CONTROLPARAMETERSTYPES_CONTROLPARAMETERS = _descriptor.Descriptor(
  name='ControlParameters',
  full_name='ndn_message.ControlParametersTypes.ControlParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ndn_message.ControlParametersTypes.ControlParameters.name', index=0,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_id', full_name='ndn_message.ControlParametersTypes.ControlParameters.face_id', index=1,
      number=105, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uri', full_name='ndn_message.ControlParametersTypes.ControlParameters.uri', index=2,
      number=114, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_uri', full_name='ndn_message.ControlParametersTypes.ControlParameters.local_uri', index=3,
      number=129, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='origin', full_name='ndn_message.ControlParametersTypes.ControlParameters.origin', index=4,
      number=111, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cost', full_name='ndn_message.ControlParametersTypes.ControlParameters.cost', index=5,
      number=106, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='capacity', full_name='ndn_message.ControlParametersTypes.ControlParameters.capacity', index=6,
      number=131, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='ndn_message.ControlParametersTypes.ControlParameters.count', index=7,
      number=132, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flags', full_name='ndn_message.ControlParametersTypes.ControlParameters.flags', index=8,
      number=108, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mask', full_name='ndn_message.ControlParametersTypes.ControlParameters.mask', index=9,
      number=112, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='ndn_message.ControlParametersTypes.ControlParameters.strategy', index=10,
      number=107, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expiration_period', full_name='ndn_message.ControlParametersTypes.ControlParameters.expiration_period', index=11,
      number=109, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='face_persistency', full_name='ndn_message.ControlParametersTypes.ControlParameters.face_persistency', index=12,
      number=133, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='base_congestion_marking_interval', full_name='ndn_message.ControlParametersTypes.ControlParameters.base_congestion_marking_interval', index=13,
      number=135, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='default_congestion_threshold', full_name='ndn_message.ControlParametersTypes.ControlParameters.default_congestion_threshold', index=14,
      number=136, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mtu', full_name='ndn_message.ControlParametersTypes.ControlParameters.mtu', index=15,
      number=137, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=597,
)

_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSE = _descriptor.Descriptor(
  name='ControlParametersResponse',
  full_name='ndn_message.ControlParametersTypes.ControlParametersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_code', full_name='ndn_message.ControlParametersTypes.ControlParametersResponse.status_code', index=0,
      number=102, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_text', full_name='ndn_message.ControlParametersTypes.ControlParametersResponse.status_text', index=1,
      number=103, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='control_parameters', full_name='ndn_message.ControlParametersTypes.ControlParametersResponse.control_parameters', index=2,
      number=104, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=600,
  serialized_end=752,
)

_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSMESSAGE = _descriptor.Descriptor(
  name='ControlParametersMessage',
  full_name='ndn_message.ControlParametersTypes.ControlParametersMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='control_parameters', full_name='ndn_message.ControlParametersTypes.ControlParametersMessage.control_parameters', index=0,
      number=104, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=754,
  serialized_end=863,
)

_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSEMESSAGE = _descriptor.Descriptor(
  name='ControlParametersResponseMessage',
  full_name='ndn_message.ControlParametersTypes.ControlParametersResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='control_response', full_name='ndn_message.ControlParametersTypes.ControlParametersResponseMessage.control_response', index=0,
      number=101, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=865,
  serialized_end=988,
)

_CONTROLPARAMETERSTYPES = _descriptor.Descriptor(
  name='ControlParametersTypes',
  full_name='ndn_message.ControlParametersTypes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_CONTROLPARAMETERSTYPES_NAME, _CONTROLPARAMETERSTYPES_STRATEGY, _CONTROLPARAMETERSTYPES_CONTROLPARAMETERS, _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSE, _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSMESSAGE, _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSEMESSAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=988,
)

_CONTROLPARAMETERSTYPES_NAME.containing_type = _CONTROLPARAMETERSTYPES
_CONTROLPARAMETERSTYPES_STRATEGY.fields_by_name['name'].message_type = _CONTROLPARAMETERSTYPES_NAME
_CONTROLPARAMETERSTYPES_STRATEGY.containing_type = _CONTROLPARAMETERSTYPES
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERS.fields_by_name['name'].message_type = _CONTROLPARAMETERSTYPES_NAME
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERS.fields_by_name['strategy'].message_type = _CONTROLPARAMETERSTYPES_STRATEGY
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERS.containing_type = _CONTROLPARAMETERSTYPES
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSE.fields_by_name['control_parameters'].message_type = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERS
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSE.containing_type = _CONTROLPARAMETERSTYPES
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSMESSAGE.fields_by_name['control_parameters'].message_type = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERS
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSMESSAGE.containing_type = _CONTROLPARAMETERSTYPES
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSEMESSAGE.fields_by_name['control_response'].message_type = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSE
_CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSEMESSAGE.containing_type = _CONTROLPARAMETERSTYPES
DESCRIPTOR.message_types_by_name['ControlParametersTypes'] = _CONTROLPARAMETERSTYPES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlParametersTypes = _reflection.GeneratedProtocolMessageType('ControlParametersTypes', (_message.Message,), dict(

  Name = _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), dict(
    DESCRIPTOR = _CONTROLPARAMETERSTYPES_NAME,
    __module__ = 'control_parameters_pb2'
    # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes.Name)
    ))
  ,

  Strategy = _reflection.GeneratedProtocolMessageType('Strategy', (_message.Message,), dict(
    DESCRIPTOR = _CONTROLPARAMETERSTYPES_STRATEGY,
    __module__ = 'control_parameters_pb2'
    # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes.Strategy)
    ))
  ,

  ControlParameters = _reflection.GeneratedProtocolMessageType('ControlParameters', (_message.Message,), dict(
    DESCRIPTOR = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERS,
    __module__ = 'control_parameters_pb2'
    # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes.ControlParameters)
    ))
  ,

  ControlParametersResponse = _reflection.GeneratedProtocolMessageType('ControlParametersResponse', (_message.Message,), dict(
    DESCRIPTOR = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSE,
    __module__ = 'control_parameters_pb2'
    # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes.ControlParametersResponse)
    ))
  ,

  ControlParametersMessage = _reflection.GeneratedProtocolMessageType('ControlParametersMessage', (_message.Message,), dict(
    DESCRIPTOR = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSMESSAGE,
    __module__ = 'control_parameters_pb2'
    # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes.ControlParametersMessage)
    ))
  ,

  ControlParametersResponseMessage = _reflection.GeneratedProtocolMessageType('ControlParametersResponseMessage', (_message.Message,), dict(
    DESCRIPTOR = _CONTROLPARAMETERSTYPES_CONTROLPARAMETERSRESPONSEMESSAGE,
    __module__ = 'control_parameters_pb2'
    # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes.ControlParametersResponseMessage)
    ))
  ,
  DESCRIPTOR = _CONTROLPARAMETERSTYPES,
  __module__ = 'control_parameters_pb2'
  # @@protoc_insertion_point(class_scope:ndn_message.ControlParametersTypes)
  ))
_sym_db.RegisterMessage(ControlParametersTypes)
_sym_db.RegisterMessage(ControlParametersTypes.Name)
_sym_db.RegisterMessage(ControlParametersTypes.Strategy)
_sym_db.RegisterMessage(ControlParametersTypes.ControlParameters)
_sym_db.RegisterMessage(ControlParametersTypes.ControlParametersResponse)
_sym_db.RegisterMessage(ControlParametersTypes.ControlParametersMessage)
_sym_db.RegisterMessage(ControlParametersTypes.ControlParametersResponseMessage)


# @@protoc_insertion_point(module_scope)
