# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rib-entry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rib-entry.proto',
  package='ndn_message',
  syntax='proto2',
  serialized_pb=_b('\n\x0frib-entry.proto\x12\x0bndn_message\"\xbb\x02\n\x0fRibEntryMessage\x12\x39\n\trib_entry\x18\x80\x01 \x03(\x0b\x32%.ndn_message.RibEntryMessage.RibEntry\x1a\x19\n\x04Name\x12\x11\n\tcomponent\x18\x08 \x03(\x0c\x1a`\n\x05Route\x12\x0f\n\x07\x66\x61\x63\x65_id\x18i \x02(\r\x12\x0e\n\x06origin\x18o \x02(\r\x12\x0c\n\x04\x63ost\x18j \x02(\r\x12\r\n\x05\x66lags\x18l \x02(\r\x12\x19\n\x11\x65xpiration_period\x18m \x01(\r\x1ap\n\x08RibEntry\x12/\n\x04name\x18\x07 \x02(\x0b\x32!.ndn_message.RibEntryMessage.Name\x12\x33\n\x06routes\x18\x81\x01 \x03(\x0b\x32\".ndn_message.RibEntryMessage.Route')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RIBENTRYMESSAGE_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='ndn_message.RibEntryMessage.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='component', full_name='ndn_message.RibEntryMessage.Name.component', index=0,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=136,
)

_RIBENTRYMESSAGE_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='ndn_message.RibEntryMessage.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='face_id', full_name='ndn_message.RibEntryMessage.Route.face_id', index=0,
      number=105, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='origin', full_name='ndn_message.RibEntryMessage.Route.origin', index=1,
      number=111, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cost', full_name='ndn_message.RibEntryMessage.Route.cost', index=2,
      number=106, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flags', full_name='ndn_message.RibEntryMessage.Route.flags', index=3,
      number=108, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expiration_period', full_name='ndn_message.RibEntryMessage.Route.expiration_period', index=4,
      number=109, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=234,
)

_RIBENTRYMESSAGE_RIBENTRY = _descriptor.Descriptor(
  name='RibEntry',
  full_name='ndn_message.RibEntryMessage.RibEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ndn_message.RibEntryMessage.RibEntry.name', index=0,
      number=7, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='routes', full_name='ndn_message.RibEntryMessage.RibEntry.routes', index=1,
      number=129, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=348,
)

_RIBENTRYMESSAGE = _descriptor.Descriptor(
  name='RibEntryMessage',
  full_name='ndn_message.RibEntryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rib_entry', full_name='ndn_message.RibEntryMessage.rib_entry', index=0,
      number=128, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RIBENTRYMESSAGE_NAME, _RIBENTRYMESSAGE_ROUTE, _RIBENTRYMESSAGE_RIBENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=348,
)

_RIBENTRYMESSAGE_NAME.containing_type = _RIBENTRYMESSAGE
_RIBENTRYMESSAGE_ROUTE.containing_type = _RIBENTRYMESSAGE
_RIBENTRYMESSAGE_RIBENTRY.fields_by_name['name'].message_type = _RIBENTRYMESSAGE_NAME
_RIBENTRYMESSAGE_RIBENTRY.fields_by_name['routes'].message_type = _RIBENTRYMESSAGE_ROUTE
_RIBENTRYMESSAGE_RIBENTRY.containing_type = _RIBENTRYMESSAGE
_RIBENTRYMESSAGE.fields_by_name['rib_entry'].message_type = _RIBENTRYMESSAGE_RIBENTRY
DESCRIPTOR.message_types_by_name['RibEntryMessage'] = _RIBENTRYMESSAGE

RibEntryMessage = _reflection.GeneratedProtocolMessageType('RibEntryMessage', (_message.Message,), dict(

  Name = _reflection.GeneratedProtocolMessageType('Name', (_message.Message,), dict(
    DESCRIPTOR = _RIBENTRYMESSAGE_NAME,
    __module__ = 'rib_entry_pb2'
    # @@protoc_insertion_point(class_scope:ndn_message.RibEntryMessage.Name)
    ))
  ,

  Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), dict(
    DESCRIPTOR = _RIBENTRYMESSAGE_ROUTE,
    __module__ = 'rib_entry_pb2'
    # @@protoc_insertion_point(class_scope:ndn_message.RibEntryMessage.Route)
    ))
  ,

  RibEntry = _reflection.GeneratedProtocolMessageType('RibEntry', (_message.Message,), dict(
    DESCRIPTOR = _RIBENTRYMESSAGE_RIBENTRY,
    __module__ = 'rib_entry_pb2'
    # @@protoc_insertion_point(class_scope:ndn_message.RibEntryMessage.RibEntry)
    ))
  ,
  DESCRIPTOR = _RIBENTRYMESSAGE,
  __module__ = 'rib_entry_pb2'
  # @@protoc_insertion_point(class_scope:ndn_message.RibEntryMessage)
  ))
_sym_db.RegisterMessage(RibEntryMessage)
_sym_db.RegisterMessage(RibEntryMessage.Name)
_sym_db.RegisterMessage(RibEntryMessage.Route)
_sym_db.RegisterMessage(RibEntryMessage.RibEntry)


# @@protoc_insertion_point(module_scope)
