# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: repo-command-parameter.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='repo-command-parameter.proto',
  package='ndn_message',
  serialized_pb='\n\x1crepo-command-parameter.proto\x12\x0bndn_message\"\xea\x04\n\x1bRepoCommandParameterMessage\x12^\n\x16repo_command_parameter\x18\xc9\x01 \x02(\x0b\x32=.ndn_message.RepoCommandParameterMessage.RepoCommandParameter\x1a\x19\n\x04Name\x12\x11\n\tcomponent\x18\x08 \x03(\x0c\x1a\x87\x01\n\tSelectors\x12\x1d\n\x15min_suffix_components\x18\r \x01(\r\x12\x1d\n\x15max_suffix_components\x18\x0e \x01(\r\x12$\n\x1cpublisher_public_key_locator\x18\x0f \x01(\x0c\x12\x16\n\x0e\x63hild_selector\x18\x11 \x01(\r\x1a\xc5\x02\n\x14RepoCommandParameter\x12;\n\x04name\x18\x07 \x01(\x0b\x32-.ndn_message.RepoCommandParameterMessage.Name\x12\x45\n\tselectors\x18\t \x01(\x0b\x32\x32.ndn_message.RepoCommandParameterMessage.Selectors\x12\x17\n\x0estart_block_id\x18\xcc\x01 \x01(\x04\x12\x15\n\x0c\x65nd_block_id\x18\xcd\x01 \x01(\x04\x12\x13\n\nprocess_id\x18\xce\x01 \x01(\x04\x12\x19\n\x10max_interest_num\x18\xd3\x01 \x01(\x04\x12\x16\n\rwatch_timeout\x18\xd4\x01 \x01(\x04\x12\x15\n\x0cwatch_status\x18\xd5\x01 \x01(\x04\x12\x1a\n\x11interest_lifetime\x18\xd6\x01 \x01(\x04')




_REPOCOMMANDPARAMETERMESSAGE_NAME = _descriptor.Descriptor(
  name='Name',
  full_name='ndn_message.RepoCommandParameterMessage.Name',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='component', full_name='ndn_message.RepoCommandParameterMessage.Name.component', index=0,
      number=8, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=173,
  serialized_end=198,
)

_REPOCOMMANDPARAMETERMESSAGE_SELECTORS = _descriptor.Descriptor(
  name='Selectors',
  full_name='ndn_message.RepoCommandParameterMessage.Selectors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_suffix_components', full_name='ndn_message.RepoCommandParameterMessage.Selectors.min_suffix_components', index=0,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_suffix_components', full_name='ndn_message.RepoCommandParameterMessage.Selectors.max_suffix_components', index=1,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='publisher_public_key_locator', full_name='ndn_message.RepoCommandParameterMessage.Selectors.publisher_public_key_locator', index=2,
      number=15, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='child_selector', full_name='ndn_message.RepoCommandParameterMessage.Selectors.child_selector', index=3,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=201,
  serialized_end=336,
)

_REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER = _descriptor.Descriptor(
  name='RepoCommandParameter',
  full_name='ndn_message.RepoCommandParameterMessage.RepoCommandParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ndn_message.RepoCommandParameterMessage.RepoCommandParameter.name', index=0,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='selectors', full_name='ndn_message.RepoCommandParameterMessage.RepoCommandParameter.selectors', index=1,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_block_id', full_name='ndn_message.RepoCommandParameterMessage.RepoCommandParameter.start_block_id', index=2,
      number=204, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_block_id', full_name='ndn_message.RepoCommandParameterMessage.RepoCommandParameter.end_block_id', index=3,
      number=205, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='process_id', full_name='ndn_message.RepoCommandParameterMessage.RepoCommandParameter.process_id', index=4,
      number=206, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_interest_num', full_name='ndn_message.RepoCommandParameterMessage.RepoCommandParameter.max_interest_num', index=5,
      number=211, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='watch_timeout', full_name='ndn_message.RepoCommandParameterMessage.RepoCommandParameter.watch_timeout', index=6,
      number=212, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='watch_status', full_name='ndn_message.RepoCommandParameterMessage.RepoCommandParameter.watch_status', index=7,
      number=213, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interest_lifetime', full_name='ndn_message.RepoCommandParameterMessage.RepoCommandParameter.interest_lifetime', index=8,
      number=214, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=339,
  serialized_end=664,
)

_REPOCOMMANDPARAMETERMESSAGE = _descriptor.Descriptor(
  name='RepoCommandParameterMessage',
  full_name='ndn_message.RepoCommandParameterMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='repo_command_parameter', full_name='ndn_message.RepoCommandParameterMessage.repo_command_parameter', index=0,
      number=201, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REPOCOMMANDPARAMETERMESSAGE_NAME, _REPOCOMMANDPARAMETERMESSAGE_SELECTORS, _REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=664,
)

_REPOCOMMANDPARAMETERMESSAGE_NAME.containing_type = _REPOCOMMANDPARAMETERMESSAGE;
_REPOCOMMANDPARAMETERMESSAGE_SELECTORS.containing_type = _REPOCOMMANDPARAMETERMESSAGE;
_REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER.fields_by_name['name'].message_type = _REPOCOMMANDPARAMETERMESSAGE_NAME
_REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER.fields_by_name['selectors'].message_type = _REPOCOMMANDPARAMETERMESSAGE_SELECTORS
_REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER.containing_type = _REPOCOMMANDPARAMETERMESSAGE;
_REPOCOMMANDPARAMETERMESSAGE.fields_by_name['repo_command_parameter'].message_type = _REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER
DESCRIPTOR.message_types_by_name['RepoCommandParameterMessage'] = _REPOCOMMANDPARAMETERMESSAGE

class RepoCommandParameterMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Name(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REPOCOMMANDPARAMETERMESSAGE_NAME

    # @@protoc_insertion_point(class_scope:ndn_message.RepoCommandParameterMessage.Name)

  class Selectors(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REPOCOMMANDPARAMETERMESSAGE_SELECTORS

    # @@protoc_insertion_point(class_scope:ndn_message.RepoCommandParameterMessage.Selectors)

  class RepoCommandParameter(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REPOCOMMANDPARAMETERMESSAGE_REPOCOMMANDPARAMETER

    # @@protoc_insertion_point(class_scope:ndn_message.RepoCommandParameterMessage.RepoCommandParameter)
  DESCRIPTOR = _REPOCOMMANDPARAMETERMESSAGE

  # @@protoc_insertion_point(class_scope:ndn_message.RepoCommandParameterMessage)


# @@protoc_insertion_point(module_scope)
